export const USUARIO_AUTENTICADO = 'USUARIO_AUTENTICADO';
export const LIMPIAR_ALERTA = 'LIMPIAR_ALERTA';
export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const REGISTRO_EXISTOSO = 'REGISTRO_EXISTOSO';
export const USUARIO_YA_EXISTE = 'USUARIO_YA_EXISTE';
export const INICIO_EXISTO = 'INICIO_EXISTO';
export const INICIO_ERROR = 'INICIO_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';

export const SUBIENDO_ARCHIVO = 'SUBIENDO_ARCHIVO';
export const SUBIR_ARCHIVO_EXITO = 'SUBIR_ARCHIVO_EXITO';
export const SUBIR_ARCHIVO_ERROR = 'SUBIR_ARCHIVO_ERROR';

export const CREAR_ENLACE_EXITO = 'CREAR_ENLACE_EXITO';
export const CREAR_ENLACE_ERROR = 'CREAR_ENLACE_ERROR';

export const LIMPIAR_STATE = 'LIMPIAR_STATE';

export const AGREGAR_PASSWORD = 'AGREGAR_PASSWORD';
export const AGREGAR_DESCARGAS = 'AGREGAR_DESCARGAS';